%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

version: '2.2'

services:

  ${dd_tpl_bn}'':
    image: 'node:20'
    volumes:
      - ${dd_cfg annosrv_appdir}':/app'
        #!^# volume_entry_expect_file: -f …/package.json
        #!^# volume_entry_expect_file: -f …/run_server.sh
        #!^# volume_entry_expect_file: -x …/run_server.sh
      - ${dd_dir}'secrets/postgres.pswd.txt:/run/secrets/postgres.pswd.txt'
        #!^# volume_entry_expect_file: -f …
    hostname: ${dd_cfg annosrv_hostname}''
    working_dir: '/app'
    command: '/app/run_server.sh'
    restart: 'always'
    environment:
        - ${dd_cfg}'anno_public_baseurl='
        - ${dd_cfg}'anno_response_timeout_sec='
        - ${dd_cfg}'anno_upload_size_limit='
        - 'anno_db_pool_host=postgres'
        - 'anno_db_pool_pswd=utf8file:/run/secrets/postgres.pswd.txt'
        - 'anno_listen_addr=0.0.0.0:8080'
    ports:
      - ${dd_cfg annosrv_dkport}':8080'


...
